apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: git-backuper

resources:
- git-backuper.yaml

configMapGenerator:
  - name: git-backuper-cm
    behavior: merge
    files:
      - config/gits-definitions
      - config/backuper-configuration
      - config/backuper.sh
